[tool.poetry]
name = "cw4"
version = "0.1.0"
description = ""
authors = ["Alexey <alexeishibakov@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
